version: '3'

services:

  mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=wordpress
    volumes:
     - db_data:/var/lib/mysql
    # networks:
    #   - my_network
    restart: always

  wordpress:
    image: wordpress
    depends_on:
      - mariadb
    links:
      - mariadb:mysql # to change later in nginx config ?
    # networks:
    #   - my_network
    environment:
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_USER=root
    ports:
      - "8000:80" # cannot change this ??
    volumes:
      - wordpress_data:/var/www/html
    restart: always

volumes:
  db_data:
  wordpress_data:
# networks:
#   my_network:
#       driver: bridge
  # nginx:
  #   image: nginx:latest
  #   container_name: my_nginx
  #   build:
  #     context: ./requirements/nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "443:443"
  #   #network:
  #   #    - current_network
  #   # volumes:
  #       # - wordpress:/.....
  #   # depends_on:
  #       # - wordpress 
  #   restart: on-failure
  #   env_file: .env
  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - requirements/nginx/conf:/etc/nginx/conf.d
  #     - /data/html:/var/www/html
  #   ports:
  #     - 8080:80
  #   links:
  #     - wordpress
  # mysql:
  #   image: mariadb
  #   container_name: my_mysql
  #   volumes:
  #     - /data/mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: mysql_root_pass
  #     MYSQL_DATABASE: db_name
  #     MYSQL_USER: user_name
  #     MYSQL_PASSWORD: user_pass
  #   restart: always

  # wordpress:
  #   image: wordpress:php7.3-fpm-alpine
  #   volumes:
  #     - /data/html:/var/www/html
  #   depends_on:
  #     - mysql
  #   environment:
  #     WORDPRESS_DB_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: mysql_root_pass
  #     WORDPRESS_DB_NAME: db_name
  #     WORDPRESS_DB_USER: user_name
  #     WORDPRESS_DB_PASSWORD: user_pass
  #     WORDPRESS_TABLE_PREFIX: wp_
  #   links:
  #     - mysql
  #   restart: always
#networks:
#    current_network:

#volumes:
#    wordpress:
#    mariadb:
#/home/login/data