version: '2.1'

services:

  mariadb:
    build: requirements/mariadb
    env_file: .env
    volumes:
     - db_data:/var/lib/mysql
    ports: 
      - "3306:3306"
    restart: "no"
    # healthcheck:
    #   test: "mysql -uwordpress -pwordpress -e 'SELECT 1;'"
    #   interval: 10s
    #   timeout: 10s
    #   retries: 15
    networks:
      my_network:

  wordpress:
    build: requirements/wordpress
    depends_on:
      - mariadb
        # condition: service_healthy
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/wordpress
    restart: always
    networks:
      my_network:

  nginx:
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wordpress_data:/var/www/wordpress
    restart: always
    networks:
      my_network:
    env_file: .env

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      device: /home/mvaldes/data/db_data
      o: bind
      type: none
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      device: /home/mvaldes/data/wordpress_data
      o: bind
      type: none
networks:
  my_network: