version: '2.1'

services:

  mariadb:
    build: requirements/mariadb
    env_file: .env
    volumes:
     - dbdata:/var/lib/mysql
    ports: 
      - "3306:3306"
    restart: always
    # healthcheck:
    #   test: "mysql -uwordpress -pwordpress -e 'SELECT 1;'"
    #   interval: 10s
    #   timeout: 10s
    #   retries: 15
    networks:
      mynetwork:

  wordpress:
    build: requirements/wordpress
    depends_on:
      - mariadb
        # condition: service_healthy
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - wordpressdata:/var/www/wordpress
    restart: always
    networks:
      mynetwork:

  nginx:
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wordpressdata:/var/www/wordpress
    restart: always
    networks:
      mynetwork:
    env_file: .env

volumes:
  dbdata:
    name: dbdata
    driver: local
    driver_opts:
      device: /home/mvaldes/data/dbdata
      o: bind
      type: none
  wordpressdata:
    name: wordpressdata
    driver: local
    driver_opts:
      device: /home/mvaldes/data/wordpressdata
      o: bind
      type: none
networks:
  mynetwork: