services:

	nginx:
		image: nginx:latest
		container_name: my_nginx
		build:
			context: ./requirements/nginx
			# dockerfile: Dockerfile
		network: current_network
		ports:
			- "443:443"
		networks:
			- current_network
		# volumes:
			# - wordpress:/.....
		# depends_on:
			# - wordpress
		restart: on-failure

	# db:
	# image: mariadb
	#  environment:
	#   - INSTALL=${INSTALL}
	#   - MARIADB_USER=${MARIADB_USER}

networks:
	current_network:

env_file: .env

volumes:
	wordpress:
	mariadb:
#/home/login/data