version: '2.1'

services:

  mariadb:
    container_name: mariadb_container
    image: mariadb
    build: requirements/mariadb
    env_file: .env
    volumes:
     - db_data:/var/lib/mysql
    ports: 
      - "3306:3306"
    restart: always
    networks:
      my_network:

  wordpress:
    container_name: wordpress_container
    image: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
        # condition: service_healthy
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/wordpress
    restart: always
    networks:
      my_network:

  nginx:
    container_name: nginx_container
    image: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
    restart: always
    networks:
      my_network:
    env_file: .env

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      device: /home/mvaldes/data/db_data
      o: bind
      type: none
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      device: /home/mvaldes/data/wordpress_data
      o: bind
      type: none
networks:
  my_network: