version: '2.1'

services:

  mariadb:
    build: requirements/mariadb
    healthcheck:
      test: "exit 0"
    env_file: .env
    volumes:
     - db_data:/var/lib/mysql
    ports: 
      - "3306:3306"
    restart: always
    networks:
      my_network:
    # healthcheck:
    #   test: ["mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"]
    #   interval: 20s
    #   timeout: 10s
    #   retries: 5

  wordpress:
    build: requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    env_file: .env
    ports:
      - "9000:9000" # cannot change this ??
    volumes:
      - wordpress_data:/var/www/wordpress
    restart: always
    networks:
      my_network:

  nginx:
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wordpress_data:/var/www/wordpress
    restart: always
    networks:
      my_network:
    env_file: .env

volumes:
  db_data:
  wordpress_data:

networks:
  my_network: